Springboot 1
YuraBondarenko/Bank pull request #1
Opened 2021-02-27 19:10 UTC by YuraBondarenko

2021-02-28 18:58 UTC, vlykhvar commented on src/main/java/com/example/bankservice/service/impl/UserServiceImpl.java
> +        return userRepository.getOne(id);
you should .orElseThrow() here.

2021-02-28 18:58 UTC, vlykhvar approved these changes

2021-03-01 10:29 UTC, KseniiaMakarova requested changes
let’s configure access to h2 database through the console in `application.properties`

2021-03-01 10:29 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservice/repository/RoleRepository.java
> +    Optional<Role> getByName(Role.RoleName name);
```suggestion
    Optional<Role> getByRoleName(Role.RoleName name);
```
Spring Data JPA is capable of automatically build the query in many cases based on the method name and parameters)

2021-03-01 10:29 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservice/service/UserService.java
> +    User update(User user);
see checklist

2021-03-01 10:29 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservice/service/impl/UserServiceImpl.java
> +        return userRepository.getOne(id);
let's call the method that join fetches roles

2021-03-01 12:11 UTC, KseniiaMakarova approved these changes

2021-03-01 12:13 UTC, merged